In [1]:
import torch
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.5.1
12.4
True


In [7]:
# size : 텐서의 모양을 확인한다.
a = torch.randn(2,3,5)

# size () 
print("size()")
print(a.size())

print("---" * 10)

# shape
# 기능은 동일하다.
print("shape")
a.shape

size()
torch.Size([2, 3, 5])
------------------------------
shape


torch.Size([2, 3, 5])

In [8]:
# reshape : 텐서의 모양을 변경합니다. 메모리를 공유하지 않습니다.


# 모양 확인
a = torch.randn(2, 3, 5)
print(a)
print(f"Shape : {a.size()}")
print("\n")


# 모양 변경
# 3차원 텐서를 2차원 텐서로 크기 변경 (2,3,5) -> (5,6)
reshape_a = a.reshape(5,6) 
print(reshape_a)
print(f"Shape : {reshape_a.shape}")

tensor([[[ 1.1270,  2.2312,  1.2686, -0.2654, -1.2141],
         [ 0.2140,  1.7289,  0.2690, -0.1020, -0.5414],
         [ 2.0980, -0.9511, -1.1540,  0.6920, -0.3194]],

        [[ 0.6923,  1.5399,  0.1340,  0.8492, -0.3098],
         [ 1.3126, -0.0884, -0.2800,  0.1481,  1.8477],
         [-0.3008,  0.0877,  0.6327,  0.8493, -0.4106]]])
Shape : torch.Size([2, 3, 5])


tensor([[ 1.1270,  2.2312,  1.2686, -0.2654, -1.2141,  0.2140],
        [ 1.7289,  0.2690, -0.1020, -0.5414,  2.0980, -0.9511],
        [-1.1540,  0.6920, -0.3194,  0.6923,  1.5399,  0.1340],
        [ 0.8492, -0.3098,  1.3126, -0.0884, -0.2800,  0.1481],
        [ 1.8477, -0.3008,  0.0877,  0.6327,  0.8493, -0.4106]])
Shape : torch.Size([5, 6])


In [ ]:
# view: 텐서의 모양을 변경합니다.
# 연속 메모리: 데이터가 일렬로 차곡차곡 붙어 저장된 상태 → view() 가능
# 비연속 메모리: 전치, 슬라이싱 등으로 메모리 순서가 뒤틀린 상태 → view() 불가, reshape() 
# 또는 .contiguous() 필요

print(a)
print(f"Shape : {a.size()}")
print("\n")

view_a = a.view(5,6)
print(view_a)
print(f"Shape : {view_a.size()}")

tensor([[[ 1.1270,  2.2312,  1.2686, -0.2654, -1.2141],
         [ 0.2140,  1.7289,  0.2690, -0.1020, -0.5414],
         [ 2.0980, -0.9511, -1.1540,  0.6920, -0.3194]],

        [[ 0.6923,  1.5399,  0.1340,  0.8492, -0.3098],
         [ 1.3126, -0.0884, -0.2800,  0.1481,  1.8477],
         [-0.3008,  0.0877,  0.6327,  0.8493, -0.4106]]])
Shape : torch.Size([2, 3, 5])


tensor([[ 1.1270,  2.2312,  1.2686, -0.2654, -1.2141,  0.2140],
        [ 1.7289,  0.2690, -0.1020, -0.5414,  2.0980, -0.9511],
        [-1.1540,  0.6920, -0.3194,  0.6923,  1.5399,  0.1340],
        [ 0.8492, -0.3098,  1.3126, -0.0884, -0.2800,  0.1481],
        [ 1.8477, -0.3008,  0.0877,  0.6327,  0.8493, -0.4106]])
Shape : torch.Size([5, 6])


In [22]:
# transpose : 텐서의 차원을 전치합니다.

# int 형식 구간 지정 텐서 생성
tensor_a = torch.randint(1, 10,(3,2,5))
print(tensor_a)
print(f"Shape : {tensor_a.size()}")
print("\n")

# (3,2,5) 를 (2,3,5) 의 크기로 변경
# 행과 열을 서로 전치, 서로 전치할 차원 2개를 지정
trans_a = tensor_a.transpose(0,1)
print(trans_a)
print(f"Shape : {trans_a.size()}")








tensor([[[9, 8, 3, 1, 2],
         [2, 8, 3, 9, 9]],

        [[8, 3, 2, 2, 4],
         [3, 2, 6, 5, 1]],

        [[3, 5, 5, 3, 6],
         [9, 9, 9, 3, 8]]])
Shape : torch.Size([3, 2, 5])


tensor([[[9, 8, 3, 1, 2],
         [8, 3, 2, 2, 4],
         [3, 5, 5, 3, 6]],

        [[2, 8, 3, 9, 9],
         [3, 2, 6, 5, 1],
         [9, 9, 9, 3, 8]]])
Shape : torch.Size([2, 3, 5])


In [ ]:
# permute : 텐서 차원의 순서를 재배열합니다.
print(tensor_a)
print(f"Shape : {tensor_a.size()}")
print("\n")

# 1 번째 차원을 2 번째 차원으로
# 2 번째 차원을 3 번째 차원으로
# 3 번째 차원을 1 번째 차원으로  
permute_a = tensor_a.permute(2,0,1) 
print(permute_a)
print(f"Shape : {permute_a.size()}")

tensor([[[9, 8, 3, 1, 2],
         [2, 8, 3, 9, 9]],

        [[8, 3, 2, 2, 4],
         [3, 2, 6, 5, 1]],

        [[3, 5, 5, 3, 6],
         [9, 9, 9, 3, 8]]])
Shape : torch.Size([3, 2, 5])


tensor([[[9, 2],
         [8, 3],
         [3, 9]],

        [[8, 8],
         [3, 2],
         [5, 9]],

        [[3, 3],
         [2, 6],
         [5, 9]],

        [[1, 9],
         [2, 5],
         [3, 3]],

        [[2, 9],
         [4, 1],
         [6, 8]]])
Shape : torch.Size([5, 3, 2])


In [ ]:
# unsqueeze : 텐서에 특정 차원에 크기가 1인 차원을 추가합니다.
tensor_a = torch.tensor([i for i in range(10)]).reshape(5,2)
print(tensor_a)
print(f"Shape : {tensor_a.size()}")
print("\n")

# 0 번째 차원 하나 추가 (5, 2) -> (1, 5 ,2)
# -1 전달 시 마지막에 차원 추가
unsqu_a = tensor_a.unsqueeze(0)
print(unsqu_a)
print(f"Shape : {unsqu_a.size()}")


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
Shape : torch.Size([5, 2])


tensor([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]])
Shape : torch.Size([1, 5, 2])


In [ ]:
# squeeze : 텐서에 차원이 크기가 1인 차원을 제거한다.
print(unsqu_a)
print(f"Shape : {unsqu_a.size()}")
print("\n") 

# 차원이 1인 차원을 제거
squ = unsqu_a.squeeze()
print(squ)
print(f"Shape : {squ.size()}")


print("-----" * 10)

# 모든 원소가 0인 5차원 크기의 텐서
x = torch.zeros(2,1,2,1,2) 
print(f"Shape : {x.size()}")
print("\n")

# 차원이 1인 차원이 여러개일 때, 모든 차원이 1인 차원 제거
print(f"Shape : {x.squeeze().size()}")
print("\n")

# 0 번째 차원의 크기가 1일 경우 삭제 / 크기가 1이 아니기에 변화 없음.
print(f"Shape : {x.squeeze(0).size()}")
print("\n")

# 1 번째 차원의 크기가 1일 경우 삭제 
print(f"Shape : {x.squeeze(1).size()}")
print('\n')

# 여러 차원 제거 가능 
print(f"Shape : {x.squeeze((0,1,3)).size()}")

tensor([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]])
Shape : torch.Size([1, 5, 2])


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
Shape : torch.Size([5, 2])
--------------------------------------------------
Shape : torch.Size([2, 1, 2, 1, 2])


Shape : torch.Size([2, 2, 2])


Shape : torch.Size([2, 1, 2, 1, 2])


Shape : torch.Size([2, 2, 1, 2])


Shape : torch.Size([2, 2, 2])


In [ ]:
# expand : 텐서의 값을 반복하여 크기를 확장합니다.
# 원본 텐서와 메모리를 공유
# A 텐서가 1차원일 경우 : A 텐서의 크기가 (m,) 이면 m은 고정하고(x,m)의 크기로만 확장 가능
# A 텐서가 2차원 이상일 경우 : 크기가 1인 차원에 대해서만 적용 가능. 

tensor_1dim = torch.tensor([1,2,3,4])
print(tensor_1dim)
print(f"Shape : {tensor_1dim.size()}")
print('\n')

# (m,) 값은 고정한 상태로 (3,4) 크기로 확장
expand_tensor = tensor_1dim.expand(3, 4)
print(expand_tensor)
print(f"Shape : {expand_tensor.size()}")


tensor([1, 2, 3, 4])
Shape : torch.Size([4])


tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
Shape : torch.Size([3, 4])


In [ ]:
# repeat : 텐서를 반복하여 크기를 확장한다.
# 원본 텐서와 메모리를 공유하지 않는다.
# A 텐서가 (m,n) 크기를 가진다하고, A 텐서를 repeat(i,j)를 하면 결과값으로 (m * i , n * j)
# 크기의 텐서가 생성된다.

tensor_1dim = torch.tensor([1,2,3,4])
print(tensor_1dim)
print(f"Shape : {tensor_1dim.size()}")
print('\n')

# repeat / tensor_1dim 자체를 행으로 3번 반복, 열로 4번 반복
repeat_tensor = tensor_1dim.repeat(3,4)
print(repeat_tensor)
print(f"Shape : {repeat_tensor.size()}")


tensor([1, 2, 3, 4])
Shape : torch.Size([4])


tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])
Shape : torch.Size([3, 16])


In [43]:
# flatten : 다차원 텐서를 1차원 텐서로 변경한다.

t = torch.tensor([[i for i in range(20)]]).reshape(2,5,2)
print(t)
print(f"Shape : {t.size()}")
print('\n')

# flatten (2,5,2) 의 tensor를 (20,)로 모양 변경, 1차원으로 변경
flat_tensor = t.flatten()
print(flat_tensor)
print(f"Shape : {flat_tensor.size()}")


print("------" *10)

# start_dim : flatten을 시작할 차원을 지정, 지정한 차원 이후로 모든 차원을 하나의 차원으로 평면화
# default = 0 (1차원)
flat_tensor2 = t.flatten(start_dim=1)
print(flat_tensor2)
print(f"Shape : {flat_tensor2.size()}")


tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]])
Shape : torch.Size([2, 5, 2])


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
Shape : torch.Size([20])
------------------------------------------------------------
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
Shape : torch.Size([2, 10])


In [44]:
# ravel : 다차원 텐서를 1차원 텐서로 변경한다.
# ravel 같은 경우에는 어떠한 축을 기준으로 변경할 수 없기 때문에 값을 넣을 수 없다.

t = torch.tensor([[i for i in range(20)]]).reshape(2,5,2)
print(t)
print(f"Shape : {t.size()}")
print('\n')

# flatten 과 같은 기능
revel_tensor = t.ravel()
print(revel_tensor)
print(f"Shape : {revel_tensor.size()}")

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]])
Shape : torch.Size([2, 5, 2])


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
Shape : torch.Size([20])


In [57]:
# cat : 주어진 차원을 따라 텐서들을 연결한다. (주어진 차원 외의 다른 차원의 크기가 같아야합니다.)

tensor_a = torch.randint(1, 10, (2, 3))
tensor_b = torch.rand(5,3)

a_cat_b_row = torch.cat((tensor_a, tensor_b), dim=0) # dim = 0 행기준 합치기
print("Concat tensor A and B Shape : " , a_cat_b_row.size())
print(a_cat_b_row)

Concat tensor A and B Shape :  torch.Size([7, 3])
tensor([[6.0000, 1.0000, 1.0000],
        [5.0000, 7.0000, 2.0000],
        [0.4275, 0.6285, 0.3073],
        [0.0394, 0.0159, 0.2518],
        [0.4974, 0.3777, 0.7800],
        [0.2621, 0.0266, 0.6758],
        [0.8644, 0.0591, 0.6278]])


In [58]:
# stack : 주어진 차원을 새로운 차원으로 추가하여 텐서들을 쌓습니다.
# 합쳐질 텐서들의 크기는 모두 같아야 한다.

tensor_a = torch.randint(1, 10, (2, 3))
tensor_b = torch.rand(2,3)

print("Tensor A Shape :", tensor_a.size())
print(tensor_a)

print('\n')

print("Tensor B Shape :", tensor_b.size())
print(tensor_b)

print('\n')

# stack dim = 0 행 기준 합치기
stack_tensor_row = torch.stack([tensor_a, tensor_b], dim=0)
print("Stack A and B :", stack_tensor_row.size())
print(stack_tensor_row)

Tensor A Shape : torch.Size([2, 3])
tensor([[9, 9, 5],
        [9, 7, 2]])


Tensor B Shape : torch.Size([2, 3])
tensor([[0.8826, 0.5987, 0.1699],
        [0.7651, 0.8638, 0.5214]])


Stack A and B : torch.Size([2, 2, 3])
tensor([[[9.0000, 9.0000, 5.0000],
         [9.0000, 7.0000, 2.0000]],

        [[0.8826, 0.5987, 0.1699],
         [0.7651, 0.8638, 0.5214]]])


In [63]:
# chunk : 나누고자 하는 텐서의 개수를 지정하여 원래의 텐서를 개수에 맞게 분리한다.
tensor_a = torch.randint(1, 10, (6,4))
print(tensor_a)

print('\n')

# 나눌 값을 지정 
chunk_num = 3 
chunk_tensor = torch.chunk(tensor_a, chunks=chunk_num, dim=0)
print(f"{len(chunk_tensor)} 개의 tensor로 분리")

print('\n')

for idx, a in enumerate(chunk_tensor):
    print(f"{idx} 번째 tensor \n{a}")
    print(f"{idx} 번째 tensor 크기 : {a.size()}")
    print("----" *10)



tensor([[4, 6, 3, 8],
        [1, 5, 1, 2],
        [2, 9, 5, 4],
        [4, 9, 1, 2],
        [3, 4, 4, 2],
        [2, 6, 6, 7]])


3 개의 tensor로 분리


0 번째 tensor 
tensor([[4, 6, 3, 8],
        [1, 5, 1, 2]])
0 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------
1 번째 tensor 
tensor([[2, 9, 5, 4],
        [4, 9, 1, 2]])
1 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------
2 번째 tensor 
tensor([[3, 4, 4, 2],
        [2, 6, 6, 7]])
2 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------


In [ ]:
# split : 입력한 크기로 여러 개의 작은 텐서로 나눈다.
# split_size_or_sections = int or list 형태로 전달가능
# chunk는 나눌 갯수를 정했다면 split은 자를 크기

tensor_a = torch.randint(1, 10, (6,4))
print(tensor_a)

print('\n')

# 나눌 값을 지정 
# int 로 값을 전달
split_num = 2 
split_tensor = torch.split(tensor_a, split_size_or_sections=split_num, dim=0)
print(f"{len(split_tensor)} 개의 tensor로 분리")

print('\n')

for idx, a in enumerate(split_tensor):
    print(f"{idx} 번째 tensor \n{a}")
    print(f"{idx} 번째 tensor 크기 : {a.size()}")
    print("----" *10)



tensor([[5, 5, 3, 9],
        [5, 3, 4, 2],
        [2, 8, 7, 4],
        [1, 3, 4, 9],
        [3, 9, 9, 5],
        [5, 6, 5, 8]])


3 개의 tensor로 분리


0 번째 tensor 
tensor([[5, 5, 3, 9],
        [5, 3, 4, 2]])
0 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------
1 번째 tensor 
tensor([[2, 8, 7, 4],
        [1, 3, 4, 9]])
1 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------
2 번째 tensor 
tensor([[3, 9, 9, 5],
        [5, 6, 5, 8]])
2 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------


In [ ]:
# split : 입력한 크기로 여러 개의 작은 텐서로 나눈다.

tensor_a = torch.randint(1, 10, (6,4))
print(tensor_a)

print('\n')

# 나눌 값을 지정 
# 리스트 형태로 전달
split_num = [2,4]
split_tensor = torch.split(tensor_a, split_size_or_sections=split_num, dim=0)
print(f"{len(split_tensor)} 개의 tensor로 분리")

print('\n')

for idx, a in enumerate(split_tensor):
    print(f"{idx} 번째 tensor \n{a}")
    print(f"{idx} 번째 tensor 크기 : {a.size()}")
    print("----" *10)


tensor([[5, 8, 5, 2],
        [4, 7, 8, 6],
        [1, 2, 1, 6],
        [4, 2, 9, 7],
        [6, 7, 3, 8],
        [9, 4, 2, 6]])


2 개의 tensor로 분리


0 번째 tensor 
tensor([[5, 8, 5, 2],
        [4, 7, 8, 6]])
0 번째 tensor 크기 : torch.Size([2, 4])
----------------------------------------
1 번째 tensor 
tensor([[1, 2, 1, 6],
        [4, 2, 9, 7],
        [6, 7, 3, 8],
        [9, 4, 2, 6]])
1 번째 tensor 크기 : torch.Size([4, 4])
----------------------------------------
