In [1]:
import torch
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# COO Sparse Tensor 

a = torch.tensor([[0, 2],[3, 0]])

# COO Sparse Tensor로 변환
a.to_sparse()

tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([2, 3]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)

In [3]:
# sparse_coo_tensor : COO형식의 sparse tensor를 생성하는 함수

# indices : 0 이 아닌 값을 가진 행, 열의 위치
# values : 0 이 아닌 값
# nnz : 0 이 아닌 값의 개수

indices = torch.tensor([[0,1,1],[2,0,1]])
values = torch.tensor([4,5,6])
sparse_tensor = torch.sparse_coo_tensor(indices= indices, values = values, size= (2,3))

print(sparse_tensor)
print('\n')

# .to_dense()는 이 희소 표현을 다시 일반적인 Dense Tensor 
# (즉, 보통 우리가 아는 일반 행렬) 로 바꿔주는 함수
print(sparse_tensor.to_dense())

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 1]]),
       values=tensor([4, 5, 6]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)


tensor([[0, 0, 4],
        [5, 6, 0]])


In [4]:
# to_sparse_csr : Dense tensor 를 CSR 형식의 Sparse tensor로 변환하는 함수

# crow_indices : 0 이 아닌 값을 가진 행의 위치 (첫번째는 무조건 0)
# col_indices : 0 이 아닌 값을 가진 열의 위치
# values : 0 이 아닌 값
# nnz : 0 이 아닌 값의 개수

t = torch.tensor([[0,0,4,3], [5,6,0,0]])
print(f"Shape : {t.size()}")
print(t)

print('\n')

# Dense tensor 를 CSR Sparse tensor 형식으로 변환
t.to_sparse_csr()

Shape : torch.Size([2, 4])
tensor([[0, 0, 4, 3],
        [5, 6, 0, 0]])




tensor(crow_indices=tensor([0, 2, 4]),
       col_indices=tensor([2, 3, 0, 1]),
       values=tensor([4, 3, 5, 6]), size=(2, 4), nnz=4,
       layout=torch.sparse_csr)

In [ ]:
# to_sparse_csc : Dense tensor 를 CSC 형식의 Sparse tensor로 변환하는 함수

# ccol_indices : 0 이 아닌 값을 가진 열의 위치 (첫번째는 무조건 0)
# row_indices : 0 이 아닌 값을 가진 열의 위치
# values : 0 이 아닌 값
# nnz : 0 이 아닌 값의 개수

t = torch.tensor([[0,0,4,3], [5,6,0,0]])
print(f"Shape : {t.size()}")
print(t)

print('\n')\

# Dense tensor 를 CSC Sparse tensor 형식으로 변환
t.to_sparse_csc()

Shape : torch.Size([2, 4])
tensor([[0, 0, 4, 3],
        [5, 6, 0, 0]])




tensor(ccol_indices=tensor([0, 1, 2, 3, 4]),
       row_indices=tensor([1, 1, 0, 0]),
       values=tensor([5, 6, 4, 3]), size=(2, 4), nnz=4,
       layout=torch.sparse_csc)

In [ ]:
# CSR Tensor 생성
# sparse_csr_tensor : CSR 형식의 Sparse tensor를 생성하는 함수
crow_indices = torch.tensor([0,2,2]) # 0이 아닌 행의 위치 (첫 번째는 무조건 0), 즉 row_pointer
col_indices = torch.tensor([0,1]) # 0이 아닌 열의 위치
values = torch.tensor([1,2]) # 0이 아닌 값
csr = torch.sparse_csr_tensor(crow_indices=crow_indices, col_indices = col_indices, values =values)


print(csr)
print('\n')
print(csr.to_dense())


tensor(crow_indices=tensor([0, 2, 2]),
       col_indices=tensor([0, 1]),
       values=tensor([1, 2]), size=(2, 2), nnz=2, layout=torch.sparse_csr)


tensor([[1, 2],
        [0, 0]])


In [ ]:
# CSC Tensor 생성
# sparse_csc_tensor : CSC 형식의 Sparse tensor를 생성하는 함수
ccol_indices = torch.tensor([0,2,2]) # 0이 아닌 열의 위치 (첫 번째는 무조건 0), 즉 column_pointer
row_indices = torch.tensor([0,1]) # 0이 아닌 행의 위치
values = torch.tensor([1,2]) # 0이 아닌 값
csc = torch.sparse_csc_tensor(ccol_indices=ccol_indices, row_indices = col_indices, values =values)


print(csc)
print('\n')
print(csc.to_dense())


tensor(ccol_indices=tensor([0, 2, 2]),
       row_indices=tensor([0, 1]),
       values=tensor([1, 2]), size=(2, 2), nnz=2, layout=torch.sparse_csc)


tensor([[1, 0],
        [2, 0]])


In [ ]:
# Sparse 와 Sparse tensor 간의 연산 (2차원) / 3차원의 sparse tensor간의 연산은 불가능 , 덧셈 곱셈은 가능
# dense도 동일하다.
# 동일한 연산 결과를 가져온다.
# 그렇기에 빅데이터를 다룰 때는 sparse tensor를 사용해야한다.
a = torch.tensor([[0,1], [0,2]], dtype=torch.float32)
b = torch.tensor([[1,0], [0,0]], dtype=torch.float32)

sparse_a = a.to_sparse()
sparse_b = b.to_sparse()

print('덧셈')
print(torch.add(a,b).to_dense() == torch.add(sparse_a, sparse_b).to_dense())

print('\n')

print('곱셈')
print(torch.mul(a,b).to_dense() == torch.mul(sparse_a, sparse_b).to_dense())

print('\n')

print('행렬곱')
print(torch.matmul(a,b).to_dense() == torch.matmul(sparse_a, sparse_b).to_dense())

덧셈
tensor([[True, True],
        [True, True]])


곱셈
tensor([[True, True],
        [True, True]])


행렬곱
tensor([[True, True],
        [True, True]])


In [19]:
# 인덱싱은 2차원 3차원 동일하게 가능
# 하지만 전체 요소를 추출할 경우 -> 에러 발생
a = torch.tensor([[0,1], [0,2 ]], dtype=torch.float)
b = torch.tensor([[[0,1], [0,2 ]], [[1,0], [0, 0]]], dtype=torch.float)

sparse_a = a.to_sparse()
sparse_b = b.to_sparse()

print('2차원 Sparse Tensor 인덱싱')
print(a[0] == sparse_a[0].to_dense())

print('\n')

print('3차원 Sparse Tensor 인덱싱')
print(b[0] == sparse_b[0].to_dense())



2차원 Sparse Tensor 인덱싱
tensor([True, True])


3차원 Sparse Tensor 인덱싱
tensor([[True, True],
        [True, True]])
