In [1]:
import torch
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [5]:
tensor_a = torch.tensor([[1, -1], [2, 3]])
tensor_b = torch.tensor([[2, -2], [3, 1]])

print('덧셈')
print(f"a+b : \n {tensor_a + tensor_b}")
print("\n")
print("torch.add(a,b)\n", torch.add(tensor_a, tensor_b))
print("----"* 10)

print('뺄셈')
print(f"a-b : \n {tensor_a - tensor_b}")
print("\n")
print("torch.sub(a,b) \n", torch.sub(tensor_a, tensor_b))
print("----"* 10)

print('곱셈')
print(f"a*b : \n {tensor_a * tensor_b}")
print("\n")
print("torch.mul(a,b)\n", torch.mul(tensor_a, tensor_b))
print("----"* 10)

print('나눗셈')
print(f"a/b : \n {tensor_a / tensor_b}")
print("\n")
print("torch.div(a,b)\n", torch.div(tensor_a, tensor_b))
print("----"* 10)

덧셈
a+b : 
 tensor([[ 3, -3],
        [ 5,  4]])


torch.add(a,b)
 tensor([[ 3, -3],
        [ 5,  4]])
----------------------------------------
뺄셈
a-b : 
 tensor([[-1,  1],
        [-1,  2]])


torch.sub(a,b) 
 tensor([[-1,  1],
        [-1,  2]])
----------------------------------------
곱셈
a*b : 
 tensor([[2, 2],
        [6, 3]])


torch.mul(a,b)
 tensor([[2, 2],
        [6, 3]])
----------------------------------------
나눗셈
a/b : 
 tensor([[0.5000, 0.5000],
        [0.6667, 3.0000]])


torch.div(a,b)
 tensor([[0.5000, 0.5000],
        [0.6667, 3.0000]])
----------------------------------------


In [6]:
# sum : 텐서의 원소들의 합을 반환
tensor_a = torch.tensor([[1,2], [3,4]])
print(tensor_a)
print(f"Shape : {tensor_a.size()}")

print('\n')

print('dim 지정 x ', torch.sum(tensor_a))
print('dim = 0 ', torch.sum(tensor_a, dim=0))
print('dim = 1 ', torch.sum(tensor_a, dim=1))

tensor([[1, 2],
        [3, 4]])
Shape : torch.Size([2, 2])


dim 지정 x  tensor(10)
dim = 0  tensor([4, 6])
dim = 1  tensor([3, 7])


In [7]:
# mean : 텐서의 원소들의 평균을 반환 
# mean 은 실수가 나올 수 있으므로 float 로 지정해주어야 함.
tensor_a = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
print(tensor_a)
print(f"Shape : {tensor_a.size()}")

print('\n')

print('dim 지정 x ', torch.mean(tensor_a))
print('dim = 0 ', torch.mean(tensor_a, dim=0))
print('dim = 1 ', torch.mean(tensor_a, dim=1))



tensor([[1., 2.],
        [3., 4.]])
Shape : torch.Size([2, 2])


dim 지정 x  tensor(2.5000)
dim = 0  tensor([2., 3.])
dim = 1  tensor([1.5000, 3.5000])


In [11]:
# max : 텐서의 원소들의 가장 큰 값을 반환
# min : 텐서의 원소들의 가장 작은 값을 반환

tensor_a = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
print(tensor_a)
print(f"Shape : {tensor_a.size()}")

print('\n')

print("max")
print('dim 지정 x ', torch.max(tensor_a))
print('dim = 0 ', torch.max(tensor_a, dim=0).values)
print('dim = 1 ', torch.max(tensor_a, dim=1).values)
print('\n')

print("-" * 20)

print('min')
print('dim 지정 x ', torch.min(tensor_a))
print('dim = 0 ', torch.min(tensor_a, dim=0).values)
print('dim = 1 ', torch.min(tensor_a, dim=1).values)

tensor([[1., 2.],
        [3., 4.]])
Shape : torch.Size([2, 2])


max
dim 지정 x  tensor(4.)
dim = 0  tensor([3., 4.])
dim = 1  tensor([2., 4.])


--------------------
min
dim 지정 x  tensor(1.)
dim = 0  tensor([1., 2.])
dim = 1  tensor([1., 3.])


In [12]:
# argmax : 텐서의 원소들의 가장 큰 값의 위치 반환
# argmin : 텐서의 원소들의 가장 작은 값의 위치 반환

tensor_a = torch.tensor([[1,2], [3,4]], dtype=torch.float32)
print(tensor_a)
print(f"Shape : {tensor_a.size()}")

print('\n')

print("max")
print('dim 지정 x ', torch.max(tensor_a))
print('dim = 0 ', torch.argmax(tensor_a, dim=0))
print('dim = 1 ', torch.argmax(tensor_a, dim=1))
print('\n')

print("-" * 20)

print('min')
print('dim 지정 x ', torch.min(tensor_a))
print('dim = 0 ', torch.argmin(tensor_a, dim=0))
print('dim = 1 ', torch.argmin(tensor_a, dim=1))

tensor([[1., 2.],
        [3., 4.]])
Shape : torch.Size([2, 2])


max
dim 지정 x  tensor(4.)
dim = 0  tensor([1, 1])
dim = 1  tensor([1, 1])


--------------------
min
dim 지정 x  tensor(1.)
dim = 0  tensor([0, 0])
dim = 1  tensor([0, 0])


In [13]:
# dot : 백터의 내적 (inner product) 반환

v1 = torch.tensor([1, 2])
u1 = torch.tensor([3, 4])

print("v1.dot(u1) : ", v1.dot(u1))
print("torch.dot(v1, u1) : ", torch.dot(v1, u1))

v1.dot(u1) :  tensor(11)
torch.dot(v1, u1) :  tensor(11)


In [16]:
# matmul : 두 텐서 간의 행렬곱 반환 
# 원소 곱과 다름 

A = torch.tensor([[1,2], [3,4]])
B = torch.tensor([[-1, 2], [1, 0]])
print("A :\n ", A)
print("B :\n ", B)

print('\n')

print('AB :\n ', torch.matmul(A,B)) # A에서 B를 행렬곱
print("BA :\n ", B.matmul(A)) # B에서 A를 행렬곱

A :
  tensor([[1, 2],
        [3, 4]])
B :
  tensor([[-1,  2],
        [ 1,  0]])


AB :
  tensor([[1, 2],
        [1, 6]])
BA :
  tensor([[5, 6],
        [1, 2]])


In [17]:
# scalar 값으로 텐서 원소 변경하기

tensor_a = torch.randn(3,2)
print("Original : \n" , tensor_a)

print('\n')

## 0 행의 모든 열을 10으로 변경하기
tensor_a[0, :] = 10
print("변경된 텐서 : \n", tensor_a)

Original : 
 tensor([[ 0.5374,  0.7376],
        [ 1.5284, -1.0753],
        [ 0.5044,  0.1333]])


변경된 텐서 : 
 tensor([[10.0000, 10.0000],
        [ 1.5284, -1.0753],
        [ 0.5044,  0.1333]])


In [18]:
# scalar 값으로 텐서 원소 변경하기

tensor_a = torch.randn(3,2)
print("Original : \n" , tensor_a)

print('\n')

## 모든 값을 tensor[0,1] 변경
tensor_a[:, :] = torch.tensor([0,1])
print("변경된 텐서 : \n", tensor_a)

Original : 
 tensor([[-1.0382,  0.1683],
        [ 0.4730, -1.1136],
        [-0.0851,  1.0655]])


변경된 텐서 : 
 tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])


In [ ]:
# 차원이 서로 다른 텐서 간의 연산

tensor_a = torch.eye(3)
print('tensor_a : \n', tensor_a)

print('\n')

tensor_b = torch.tensor([1,2,3])
print('tensor_b : \n', tensor_b)

print('\n')

print('a + b : \n', tensor_a + tensor_b)


tensor_a : 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


tensor_b : 
 tensor([1, 2, 3])


a + b : 
 tensor([[2., 2., 3.],
        [1., 3., 3.],
        [1., 2., 4.]])


In [ ]:
# 차원이 맞지 않는 경우, 차원을 추가하여 broadcating으로 텐서 간의 계산을 할 수 있다.
tensor_a = torch.randn(3,2,5)
mean_a = tensor_a.mean(2) # 열 기준 평균값

print(f"tensor size : {tensor_a.size()}, mean size : {mean_a.size()}")

print('\n')

print(tensor_a - mean_a) # error 발생 차원이 달라서 계산 불가능


tensor([[[ 0.4106, -0.7186,  1.0626,  0.0818,  0.5512],
         [ 0.1739,  1.8655, -0.2832,  0.4819,  0.4771]],

        [[-0.0227, -0.1563, -0.8777, -1.9394,  1.5576],
         [ 0.3707,  0.7164,  0.1423,  0.1092,  0.7987]],

        [[ 0.1426, -1.5565,  1.2994,  0.7434,  0.1057],
         [ 1.8407,  1.5982,  0.1855, -1.3703,  0.2949]]])


tensor([[ 0.2775,  0.5430],
        [-0.2877,  0.4274],
        [ 0.1469,  0.5098]])


In [24]:
# 차원이 다를 경우 해결 방법
unseq_mean = mean_a.unsqueeze(-1) # 마지막 축 추가 (3, 2 ,1)
print(unseq_mean.size())

print('\n')


print(tensor_a - unseq_mean) # (3, 2, 5) - (3, 2 ,1) 계산 가능



torch.Size([3, 2, 1])


tensor([[[ 0.1331, -0.9961,  0.7851, -0.1957,  0.2736],
         [-0.3692,  1.3225, -0.8262, -0.0611, -0.0660]],

        [[ 0.2650,  0.1314, -0.5900, -1.6517,  1.8453],
         [-0.0567,  0.2889, -0.2852, -0.3183,  0.3713]],

        [[-0.0044, -1.7034,  1.1525,  0.5964, -0.0412],
         [ 1.3309,  1.0884, -0.3243, -1.8801, -0.2149]]])
