In [1]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.5.1
12.4
True


In [2]:
import numpy as np
import warnings 
warnings.filterwarnings('ignore')


In [ ]:
# 텐서의 값을 무작위로 생성하는 방법
# 0 부터 1 사이의 값을 랜덤하게 NxM 텐서로 반환
torch.rand(2, 3)

tensor([[0.6996, 0.1080, 0.5712],
        [0.7624, 0.5089, 0.1848]])

In [4]:
# randn 평균이 0이고 표준편차가 1인 정규 분포(가우시안 분포)에서 무작위로 생성된 텐서를 반환
torch.randn(2, 3)

tensor([[ 1.2204,  0.5394,  1.5100],
        [ 1.2632,  0.6275, -0.7197]])

In [ ]:
# randint 주어진 범위 내에서 정수값을 무작위로 선택하여 텐서를 생성
torch.randint(1, 10, (5,5)) # 최소값 = 1 , 최대값 = 9 , (5x5) Tensor 크기  

tensor([[5, 8, 5, 7, 8],
        [7, 3, 4, 2, 9],
        [8, 3, 6, 1, 3],
        [7, 5, 1, 4, 9],
        [6, 2, 7, 4, 6]])

In [ ]:
# 0의 값을 가지는 NxM 텐서를 생성
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# 1의 값을 가지는 NxM 텐서를 생성
torch.ones(3,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
# 모든 요소가 지정된 값의 텐서로 반환
torch.full((2,3,2),10) # torch.full((*size),value)

tensor([[[10, 10],
         [10, 10],
         [10, 10]],

        [[10, 10],
         [10, 10],
         [10, 10]]])

In [ ]:
# eye : 단위 행렬 반환(단위 행렬 ? : 대각선 요소가 1이고, 나머지는 전부 0인 행렬)
torch.eye(10) # nxn의 대각선 요소가 1인 행렬을 반환

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
# tensor : 주어진 데이터를 텐서로 변환. 데이터는 list, tuple, numpy array등의 형태일 수 있음
ls = [[1,3,2,5], [2,4,6,7]]
tup = tuple([1,2,3])
arr = np.array([[[1,2,3], [2,4,6], [3,5,7]],[[5,6,7],[6,7,8],[7,1,2]]])
dic = {1 : 1, 2 : 2}
sett = {1,2,3,4}

# 타입 확인
print(type(ls))
print(type(tup))
print(type(arr))
print(type(dic))
print(type(sett))

# list, tuple, array 같은 경우에는 텐서 변환이 가능하지만
# dic 같은 경우는 key : value 로 저장 되기 때문에 tensor로 변환시에 list로 변환 후 값만 따로 불러와야한다.
# set는 순서가 없는 자료 이기 때문에 내부 요소의 순서를 확정할 수 없음 
# torch는 set 자체를 배열로 간주할 수 없음 그렇기에 set도 list로 변환 후에 tensor로 변환을 해야함
print(torch.tensor(ls))
print(torch.tensor(tup))
print(torch.tensor(arr))
print(torch.tensor(list(dic.values())))
print(torch.tensor(list(sett)))


<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'dict'>
<class 'set'>
tensor([[1, 3, 2, 5],
        [2, 4, 6, 7]])
tensor([1, 2, 3])
tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 5, 7]],

        [[5, 6, 7],
         [6, 7, 8],
         [7, 1, 2]]])
tensor([1, 2])
tensor([1, 2, 3, 4])


In [ ]:
# # from_numpy(arr) : numpy_array를 텐서로 변환 , numpy 배열만 가능
# # torch.tensor와 torch.from_numpy의 차이점은 tensor는 arr에 대한 복사본을 만들지만,
# # from_numpy는 arr와 메모리를 공유한다. arr가 바뀌면 같이 바뀜
# # as.tensor : from_numpy와 동일한 기능을 하지만 list나 tuple등도 가능하다
# # 하지만 numpy_array가 아닌 list, tuple 등이 파라미터로 전달된다면 copy한다.
t1 = torch.tensor(arr)
t2 = torch.from_numpy(arr)
t3 = torch.as_tensor(ls)

arr[0][0][0] = 99
print(t1) # tensor 독립적
print(t2) # from_numpy 메모리 공유

# # list 메모리 공유 x
ls[0][0] = 99
print(t3)
# # 데이터가 크고 복사 비용이 아까울 때 from_numpy를 사용

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 5, 7]],

        [[5, 6, 7],
         [6, 7, 8],
         [7, 1, 2]]])
tensor([[[99,  2,  3],
         [ 2,  4,  6],
         [ 3,  5,  7]],

        [[ 5,  6,  7],
         [ 6,  7,  8],
         [ 7,  1,  2]]])
tensor([[1, 3, 2, 5],
        [2, 4, 6, 7]])


In [69]:
# torch.Tensor : float 32 type으로 텐서 변환
# torch.tensor : default int 64 


# tensor 변환
data = [1,2,3,4,5]
tensor1 = torch.tensor(data) # list 에서 tensor 변환
print("torch.tensor")
print(f"Output : {tensor1}")
print(f"Type : {tensor1.dtype}")

print("-" * 20)

# Tensor 변환
tensor2 = torch.Tensor(data)
print("torch.Tensor")
print(f"Output : {tensor2}")
print(f"Type : {tensor2.dtype}")

print("-" * 20)

# tensor 인자에 dtype=torch.float32를 사용해도 된다
tensor3 = torch.tensor(data, dtype=torch.float32)
print("torch.tensor(data, dtype=torch.float32)")
print(f"Output : {tensor3}")
print(f"Type : {tensor3.dtype}")

torch.tensor
Output : tensor([1, 2, 3, 4, 5])
Type : torch.int64
--------------------
torch.Tensor
Output : tensor([1., 2., 3., 4., 5.])
Type : torch.float32
--------------------
torch.tensor(data, dtype=torch.float32)
Output : tensor([1., 2., 3., 4., 5.])
Type : torch.float32


In [71]:
# indexing 
# 1차원 텐서 생성
tmp_1dim = torch.tensor([i for i in range(10)])

print(tmp_1dim[0])
print(tmp_1dim[5])
print(tmp_1dim[-1])

tensor(0)
tensor(5)
tensor(9)


In [ ]:
# 3차원 텐서에서 indexing 
tmp_3dim = torch.randn(4, 3, 2)
print("Shape :", tmp_3dim.shape)
print(tmp_3dim)

print("---------"* 5)

# 첫 번째 차원(:) : 모든 요소를 다 가져와라
# 두 번째 차원(:) : 모든 요소를 다 가져와라
# 세 번재 차원(index=0) : 0 번째 요소를 선택해라.
print(tmp_3dim[:,:,0].shape)
print(tmp_3dim[:,:,0])

print("---------"* 5)

# 첫 번째 차원(index=0): 0번째 요소를 선택해라.
# 두 번째 차원(:) : 모든 요소를 다 가져와라.
# 세 번째 차원(index=1): 1번째 요소를 선택해라.
print(tmp_3dim[0,:,1].shape)
print(tmp_3dim[0,:,1])


Shape : torch.Size([4, 3, 2])
tensor([[[ 0.1034, -2.2368],
         [-0.9531,  1.1428],
         [-0.8397,  0.2901]],

        [[ 0.2857,  1.3905],
         [-1.5626,  0.9629],
         [ 0.6374, -0.2289]],

        [[ 1.0221,  0.6144],
         [-1.6259, -1.7859],
         [ 0.7424, -0.1931]],

        [[-0.9202,  0.1935],
         [ 0.5086,  0.1112],
         [-1.0196, -0.2406]]])
---------------------------------------------
torch.Size([4, 3])
tensor([[ 0.1034, -0.9531, -0.8397],
        [ 0.2857, -1.5626,  0.6374],
        [ 1.0221, -1.6259,  0.7424],
        [-0.9202,  0.5086, -1.0196]])
---------------------------------------------
torch.Size([3])
tensor([-2.2368,  1.1428,  0.2901])


In [ ]:
# index_select : 선택한 차원에서 인덱스에 해당하는 요소만 추출하는 함수
# 기본 문법 
# index_select(input, dim, index)
# dim : 0(행), 1(열), 2(깊이 기준)

# 2차원 텐서 생성
tmp_2dim = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(tmp_2dim)


# 
my_index = torch.tensor([0, 2])
torch.index_select(tmp_2dim, dim=1, index= my_index)


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


tensor([[ 0,  2],
        [10, 12]])

In [ ]:
# Masking 을 이용한 indexing: 조건에 따른 텐서의 요소를 사용하기 위한 방법으로 조건에 맞는 요소들만 반환하는 방법
# 불리언 텐서로 반환
mask = tmp_2dim >= 5
print(mask)

print("\n")

# mask 적용
tmp_2dim[mask]

tensor([[False, False, False, False, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]])




tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [96]:
# masked_select : 주어진 mask에 해당하는 요소들을 추출하여 1차원으로 펼친 새로운 텐서를 반환하는 함수
# 기본 문법 
# torch.masked_select(input, mask)
torch.masked_select(tmp_2dim, mask = mask) 

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# take : 주이진 인덱스를 사용하여 텐서에서 요소를 선택하는 함수. 인덱스 번호는 텐서를 1차원으로 늘려졌을 때 기준으로 접근해야한다.
tmp_2dim = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(tmp_2dim)

print("\n")

# tensor가 1차원으로 늘려졌을 때 기준으로 index 번호로 접근
my_index = torch.tensor([0, 15])
torch.take(tmp_2dim, index = my_index)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])




tensor([ 0, 15])

In [102]:
# gather : 주어진 차원에서 인덱스에 해당하는 요소들을 선택하여 새로운 텐서를 반환
tmp_2dim = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(tmp_2dim)
print("\n")

# 0 번째 값, 2번째 값을 0번째 행으로 설정하고, 5번째 값, 3번째 값을 1번째 행으로 설정한다.
recon_index = torch.tensor([[0,2], [5, 3]])
print(recon_index)
print("\n")

dim = 1 # 열 기준
torch.gather(tmp_2dim, dim=dim, index = recon_index)


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


tensor([[0, 2],
        [5, 3]])




tensor([[ 0,  2],
        [15, 13]])